

server:
  port: 8081

spring:
  datasource:
    url : jdbc:mysql://localhost/swami_sales
    username: root
    password: password
    driver-class-name : com.mysql.cj.jdbc.Driver
    tomcat :
      initial-size : 15
      max-wait : 30000
      max-active: 1000
      max-idle: 15
      min-idle : 8
      default-auto-commit : true

  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085/


  jpa:
    show-sql : true



# for default global circuit breakers.
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 6s
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 10

  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true

  ratelimiter:
    configs:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 1s
        timeoutDuration: 1s

# you can also auto retry with resilience4j
