

server:
  port: 8081
  address: 192.168.1.26

spring:
  datasource:
    url : jdbc:mysql://localhost/swami_sales
    username: root
    password: password
    driver-class-name : com.mysql.cj.jdbc.Driver
    tomcat :
      initial-size : 15
      max-wait : 30000
      max-active: 1000
      max-idle: 15
      min-idle : 8
      default-auto-commit : true

  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085/


  jpa:
    show-sql : true

jwt:
  secret: javainuse




