

server :
  port : 8080

spring:
  application:
    name: API_GETAWAY
  cloud:
    gateway:
      routes:
        - id: WHOLESALE-SERVICE
          uri: lb://WHOLESALE-SERVICE
          predicates:
            - Path=/wholesale/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
